namespace VehiclesAccounting.Core.Services 
{
    public enum SortState
    {
        NameAsc,
        NameDesc,
        SurnameAsc,
        SurnameDesc,
        PatronymicAsc,
        PatronymicDesc,
        AgeAsc,
        AgeDesc,
        PostAsc,
        PostDesc,
        ProducerAsc,
        ProducerDesc,
        CountryAsc,
        CountryDesc,
        CategoryAsc,
        CategoryDesc,
        DateStartAsc,
        DateStartDesc,
        RegistrationNumberAsc,
        RegistrationNumberDesc,
        TechPassportNumberAsc,
        TechPassportNumberDesc,
        DateInspectionAsc,
        DateInspectionDesc,
        TheftDateAsc,
        TheftDateDesc,
        MarkAboutFindingAsc,
        MarkAboutFindingDesc,
        BodyNumberAsc,
        BodyNumberDesc
    }
}
